customhost = "employee.c3iwpfovny7b.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yeohchiheng-employee"
customregion = "us-east-1"
